service: email-service

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  timeout: 30

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline